# Set up MySQL
# See:
# https://stackoverflow.com/questions/26597926/install-mysql-with-ansible-on-ubuntu
# https://serverfault.com/questions/891373/unable-to-create-mysql-database-through-ansible
---
- name: Install MySQL server
  apt:
    state: present
    update_cache: yes
    name:
      - mysql-server
  tags:
    - mysql

- name: Install additional MySQL packages
  apt:
    state: present
    update_cache: yes
    name:
      - mysql-client
      - libmysqlclient-dev
      - python-pymysql
  tags:
    - mysql

- name: Install python3-pip
  apt:
    state: present
    update_cache: yes
    name:
      - python3-pip
  tags:
    - mysql

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
  tags:
    - mysql

- name: Set the MySQL service state
  service:
    name: mysql
    state: started
    enabled: true
  tags:
    - mysql

- name: Copy MySQL root credentials as .my.cnf file
  template:
    src: root_mysql_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: "0400"
  tags:
    - mysql

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify:
    - Restart MySQL
  tags:
    - mysql

- name: Ensure anonymous user(s) are not in the database
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  notify:
    - Restart MySQL
  tags:
    - mysql

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  notify:
    - Restart MySQL
  tags:
    - mysql

- name: Create app database
  mysql_db:
    name: "{{ mysql_database_name }}"
    state: present
    collation: utf8_general_ci
    encoding: utf8
  notify:
    - Restart MySQL
  tags:
    - mysql

- name: Create app database user
  mysql_user:
    name: "{{ mysql_database_user }}"
    password: "{{ mysql_user_password }}"
    priv: "*.*:ALL"
    host: localhost
  notify:
    - Restart MySQL
  tags:
    - mysql
